---
# tasks file for kube-deps

- name: Disable swap
  shell: |
    swapoff -a
  become: yes
- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  become: yes
